//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 3:05:26 PM on Wednesday, January 24, 2001
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"SSC2 Library"
//
//	Palm App Version: 		"0.1"



//	Resource: tFRM 1000
#define UntitledForm                              1000

